import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased !max-w-[100vw]`}>
        <Navbar />
        <div className="max-w-screen-xl mx-auto px-5 md:px-8 xl:px-5">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
